[package]
name = "dims_core"
version = "0.1.0"
authors = ["william"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["f32"]
f32 = []
f64 = []